---
title: "Workshop Exercise: Grouping, Summarizing and Plotting"
author: "James Matosse"
---

## Data Preparation

### Load Packages

To get started, **load in the needed packages**: pandas, numpy, plotly express.

```{python}
import pandas as pd
import numpy as np
import plotly.express as px
```

### Import Data

Download the `india_tuberculosis.csv` file from the course portal and save it in your `data` folder.

Now, **read in the `india_tuberculosis` dataset into Python from your data folder** into a DataFrame called `tb`. The DataFrame you import should have 880 rows and 21 columns. Remember to use relative paths to allow your script to use project-relative paths.

```{python}
# Import the CSV file

tb = pd.read_csv("../data/india_tuberculosis.csv")
tb
```

Run the following line of code to convert all column names to lowercase and replace spaces with underscores:

```{python}
tb.columns = tb.columns.str.lower().str.replace(' ', '_')
tb.columns
```

### Calculate Total Cost

Each patient record notes the location and cost of up to three visits. Add together these costs (`first_visit_cost`, `second_visit_cost`, and `third_visit_cost`) to create a `total_cost` variable.

```{python}
# Calculate total cost
tb["total_cost"] = (
    tb["first_visit_cost"] + tb["second_visit_cost"] + tb["third_visit_cost"]
)
tb
```

## Investigating Healthcare Costs by Education Level

### Reorder Education Levels

Before moving further, let's take a closer look at the `education` variable in our dataset:

```{python}
# Count unique values of education levels
tb["education"].value_counts()
```

You'll notice that education levels are ordered alphabetically by default! However, in this case, it would be more useful to reorder the education levels so that they are arranged in a chronological order.

First, use the `replace()` method to convert the "Graduate & Above" values to "Graduate".

```{python}
tb["education"] = tb["education"].replace({"Graduate & Above": "Graduate"})
tb["education"].value_counts()
```

Now, run the code below to reorder the education levels by converting the `education` variable into a categorical variable with the levels defined in a specific order:

```{python}
education_levels = [
    "No Education",
    "Primary",
    "Middle",
    "Secondary",
    "Higher Secondary",
    "Graduate",
    "Missing",
]

tb["education"] = pd.Categorical(
    tb["education"], categories=education_levels, ordered=True
)
```

Now, inspect the `education` variable again to make sure it has been reordered correctly:

```{python}
tb["education"].value_counts()
```

We will use the newly transformed `education` variable for grouping, summarizing, and plotting below.

### Table of Costs by Education Level

Let's compare the cost of treatment at different health facilities using a summary table. Use pandas methods to group by education level and create a summary table with two variables:

- The number of patients in each education level
- The mean total cost for each education level

Store the resulting DataFrame as an object called `edu_cost_table`.

```{python}
# Create summary table
edu_cost_table = (
    tb.groupby("education")
    .agg(mean_tot_cost=("total_cost", "mean"), num_inds=("total_cost", "size"))
    .reset_index()
)
edu_cost_table
```

Reorder the rows of the summary table to go from highest to lowest mean cost. You can use the `sort_values()` method to do this.

```{python}
# Reorder summary table
edu_cost_table = edu_cost_table.sort_values(["mean_tot_cost"], ascending=False)
edu_cost_table
```

Which education level has the highest mean total cost of treatment?

YOUR ANSWER HERE: The Graduate education level

Below, we will visualize the data with a plot to see if there is a relationship between education level and healthcare costs.

### Visualize Costs by Education Level

Using `plotly.express` and the costs summary table you created earlier, create a bar plot of mean costs by education level. It should be sorted from lowest education level to highest education level.

```{python}
px.bar(
    edu_cost_table,
    y="mean_tot_cost",
    x="education",
    category_orders={"education": education_levels},
    title="The mean treatment Costs by Education level",
    labels={"mean_tot_cost": "Mean Total Cost", "education": "Education"},
)

```

Write a short interpretation of the plot.
Answer: The lowest mean cost is equivalent to the lowest education level. The higher secondary level has lower mean cost to the secondary level.

## Investigating Healthcare Costs by Age Group

### Create an `age_group` Variable

The `age` variable records the age of each patient in years. We want to classify the patients into four approximately equally-sized age groups for further analysis.

First, run the code below to determine the quantiles of the `age` variable to decide the cutoffs for each age group:

```{python}
# Determine quantiles of age
tb["age"].describe()
```

Based on the quantile markers (min, 25%, 50%, 75%, max), we can note the following four age groups with approximately equal numbers of patients:

- 18-36
- 37-47
- 48-57
- 58+

Use a custom function called `assign_age_group()`, then vectorize it using `np.vectorize()` and apply it to the `age` variable to create an `age_group` variable.

(If you prefer, you can also use `pd.cut()` to create the `age_group` variable.)

```{python}
def assign_age_group(age):
    if age >= 18 and age < 37:
        return "18-36"
    elif age >= 37 and age < 48:
        return '37-47'
    elif age >= 48 and age < 58:
        return "48-57"
    elif age >= 58:
        return '58+'
    else:
        return 'Invalid'

assign_age_group(20)
assign_age_groupVec = np.vectorize(assign_age_group)

tb["age_group"] = assign_age_groupVec(tb["age"])
tb
```

#### Using pd.cut() age group

```{python}
# Creating bin age into 4 intervals
nbins = [17, 36, 47, 57, 100]
categories_auto = pd.cut(tb["age"], nbins)

# Print the results
# print(categories_auto)
categories_auto.value_counts(normalize=True)
```

Now, check if we met our goal of having a similar number of patients in each age group using the `value_counts()` method:

```{python}
# Tabulate age groups
tb["age_group"].value_counts(normalize=True)
```

**Checkpoint:** If you classified the age groups correctly, you will see that each age group has approximately 24-26% of the patients.

### Table of Costs by Age Group

Next, summarize the total healthcare costs by age group. Use pandas methods to group by `age_group` and create a summary table with two variables:

- The number of patients in each age group
- The mean total cost for each age group

Store the resulting DataFrame as an object called `age_cost_table`.

```{python}
# Create summary table for age groups
age_cost_table = (
    tb.groupby("age_group")
    .agg(mean_tot_cost_age=("total_cost", "mean"), num_inds=("total_cost", "size"))
    .reset_index()
)
age_cost_table
```

### Visualize Costs by Age Group

Using `plotly.express` and the costs summary table you created earlier, create a bar plot of mean costs by age group.

```{python}
px.bar(
    age_cost_table,
    x="age_group",
    y="mean_tot_cost_age",
    title="Mean treatment Costs by Age group",
    labels={"age_group": "Age Group", "mean_tot_cost_age": "Mean Total Cost"},
)
```

Write a short interpretation of the plot.
Answer: The young (18-36) group has the highest mean cost of treatment followed by the elderly(58+) group and the lowest mean cost is for the 48-57 age group.

## Bonus Challenge (Optional and Ungraded)

If you finish early and have extra time, you can explore and transform the dataset further.

We can look at two types of health facilities in the dataset: private and public (government).

```{python}
# List of healthcare locations
tb["first_visit_location"].unique()
```

Note: PHC = primary health center, GH = govt hospital, etc.

### Comparing Delays in Public vs Private Health Facilities

Let's create a new variable indicating whether a healthcare location is private or public. We can do this using the `str.contains()` function from pandas.

```{python}
tb["first_visit_type"] = np.where(
    tb["first_visit_location"].str.contains("Pvt"), "Private", "Public"
)
```

Inspect the new variable in `tb`.

```{python}
tb
```

Your assignment for this challenge is to summarize delays in treatment and compare the length of delays between private and public health facilities.

You can start by making a summary table of `treatment_initiation_delay_in_days`, grouped by `first_visit_type`. Then visualize the data and draw insights from your findings.

```{python}
# tb['treatment_initiation_delay_in_days'] =
(
    tb.groupby("first_visit_type")
    .agg(
        mean_delays=("treatment_initiation_delay_(in_days)", "mean"),
        min_delays=("treatment_initiation_delay_(in_days)", "min"),
        max_delays=("treatment_initiation_delay_(in_days)", "max"),
    )
    .reset_index()
)
```

```{python}
px.box(
    tb,
    x="first_visit_type",
    y="treatment_initiation_delay_(in_days)",
    points="all",
    title="Delays in treatment between private and public health facilities",
    labels={
        "treatment_initiation_delay_(in_days)": "Start Treatment delays (in days)",
        "first_visit_type": "Health Facility Type",
    },
)
```

The Public facilities have a median of 6 days with an average of 9.27 days in the delay to initiate treatment. While the private facilities have median of 5 day with an average of 8.43 days. The upper fence of the whiskers are 26 days and 20 days, respectively. The largest range of 110 days is attributed to a  private facility with a significant amount of data points being treated as outliers for the private sector.

## Wrap Up

That's it for this assignment! Feel free to explore further and share your findings.